import { ScrollView, Text, View } from 'react-native'

// Cada componente se llama como su archivo .tsx
export function Saludo(){
    return <ScrollView>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
        <Text>Hola desde React Native + Expo</Text>
    </ScrollView>
}
